#!/bin/bash

vol="/opt/binder/var/binderhub"
cfg="/opt/binder/etc/binderhub_config.py"

echo ":: Sourcing conda environment"
if [ -f /opt/binder/etc/profile.d/conda.sh ]
then
    . /opt/binder/etc/profile.d/conda.sh
    conda activate base
fi

echo ":: Checking for persistent volume"
if [ ! -d "${vol}" ]
then
    echo "binderhub data directory doesn't exist. Exiting." 1>&2
    exit 1
fi
cd ${vol}

echo ":: Checking for configuration file"
if [ ! -f "${cfg}" ]
then
    echo "Failed to find binderhub config file. Exiting." 1>&2
    exit 1
fi

python3 -m binderhub --config ${cfg}
