#!/bin/bash

vol="/opt/conda/var/binderhub"
cfg="/opt/conda/etc/binderhub_config.py"

echo ":: Sourcing conda environment"
if [ -f /opt/conda/etc/profile.d/conda.sh ]
then
    . /opt/conda/etc/profile.d/conda.sh
    conda activate base
fi

echo ":: Checking for persistent volume"
if [ ! -d "${vol}" ]
then
    echo "binderhub data directory doesn't exist. Exiting." 1>&2
    exit 1
fi
cd ${vol}

echo ":: Checking for configuration file"
if [ ! -f "${cfg}" ]
then
    echo "Failed to find binderhub config file. Exiting." 1>&2
    exit 1
fi

echo ":: Initializing container registry"
SEARCH=`podman search --list-tags buildpack-deps 2> /dev/null`
FOUND=1
if [[ "$?" -eq 0 ]]; then
    IMAGE_SPEC=`echo $SEARCH | tr '/' ' ' | cut -d' ' -f 4-5`
    if [[ $IMAGE_SPEC == "buildpack-deps bionic" ]]; then
        echo "Registry previously initialized."
        FOUND=0
    fi
fi
if [[ "$FOUND" -eq 1 ]]; then
    IMAGE_ID=`podman pull docker.io/library/buildpack-deps:bionic`
    podman push ${IMAGE_ID} registry:5000/buildpack-deps:bionic
fi

echo "::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"

python3 -m binderhub --config ${cfg}
