#!/bin/bash

vol="/opt/jupyterhub/var/jupyterhub"
cfg="/opt/jupyterhub/etc/jupyterhub_config.py"

echo ":: Sourcing 'conda' environment"
conda activate /opt/jupyterhub

echo ":: Checking for persistent volume"
if [ ! -d "${vol}" ]
then
    echo "Jupyterhub data directory doesn't exist. Exiting." 1>&2
    exit 1
fi
cd ${vol}

echo ":: Checking for configuration file"
if [ ! -f "${cfg}" ]
then
    echo "Failed to find jupyterhub config file. Exiting." 1>&2
    exit 1
fi

echo ":: Checking for 'jupyterhub' executable"
command -v jupyterhub > /dev/null 2>&1
if [ ! $? == 0 ]
then
    echo "Failed to find jupyterhub executable. Exiting." 1>&2
    exit 1
fi

jupyterhub -f ${cfg}
