#!/bin/bash

vol="/opt/jupyter/var/jupyterhub"
cfg="/opt/jupyter/etc/jupyterhub_config.py"
exe="/opt/jupyter/bin/jupyterhub"

echo ":: Sourcing conda environment"
if [ -f /opt/jupyter/etc/profile.d/conda.sh ]
then
    . /opt/jupyter/etc/profile.d/conda.sh
    conda activate base
fi

echo ":: Checking for persistent volume"
if [ ! -d "${vol}" ]
then
    echo "Jupyterhub data directory doesn't exist. Exiting." 1>&2
    exit 1
fi
cd ${vol}

echo ":: Checking for configuration file"
if [ ! -f "${cfg}" ]
then
    echo "Failed to find jupyterhub config file. Exiting." 1>&2
    exit 1
fi

echo ":: Checking for 'jupyterhub' executable"
if [ ! -e "${exe}" ]
then
    echo "Failed to find jupyterhub executable. Exiting." 1>&2
    exit 1
fi

${exe} --debug -f ${cfg}
